spring:
  application:
    name: webshop

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:webshop;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: info
